# Generated by Django 5.1.1 on 2025-01-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequest',
            old_name='description',
            new_name='issue_description',
        ),
        migrations.RemoveField(
            model_name='customerrequest',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='customerrequest',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
