# Generated by Django 5.1.1 on 2025-01-19 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_rename_description_customerrequest_issue_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequest',
            old_name='name',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customerrequest',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customerrequest',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='customerrequest',
            name='address',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='customer_name',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('resolved', 'Resolved')], default='submitted', max_length=10),
        ),
    ]
