# Generated by Django 5.1.1 on 2025-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_name_customerrequest_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='tentative_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
