# Generated by Django 5.1.1 on 2025-01-20 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_remove_customerrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
