# Generated by Django 5.1.1 on 2025-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_customerrequest_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
